### ISSUE TITLE
Roadmap Permanente

### ISSUE THREAD

**Issue by thlmenezes** [thlmenezes/cicfighters-py3#1]
Olá, essa é uma issue que será mantida _permanentemente_ aberta para documentar, acompanhar e priorizar ideias de melhorias.

Caso algo da lista lhe interesse, crie uma issue separada para que seja discutido a parte e melhor definidos os critérios de aceitação, podem ser criadas novas issues clicando à direita dos nomes dos itens da lista.

## Abertas

- [ ] Adicionar seção "Agradecimentos" ao README
    - reconhecimento destacando os autores da obra original
- [ ] Incluir assets na build do jogo
    - Modificar action de build para incluir modificações em assets em eventos que a acionam
- [ ] Limitar criação de novas builds a alterações nos arquivos do jogo
- [ ] Remover evento de criação de build para push main
- [ ] Modificar build action para incluir artefatos em releases
    - Adicionar artefatos à releases automaticamente
- [ ] Configurar black como formatador
    - adicionar nas dependências de desenvolvimento (requirements-dev.txt)
    - atualizar comando de instalar dependências da seção "Contribuindo" do README
- [ ] Criar Makefile
    - Comandos: lint, fix, build, clean e help
- [ ] Criar action de lint para todo PR para main
- [ ] Adicionar PR template
- [ ] Adicionar Issue template
- [ ] Criar pacote CiCfighters
    - Incluir estrutura de pastas baseada em outros projetos Python
- [ ] Refatorar GameMenu
- [ ] Refatorar VersusScreen
- [ ] Refatorar Ringue
- [ ] Adicionar build CiCfighters em 32 bits às releases
- [ ] Adicionar suporte a joystick

## Concluídas

N/A
